version: '3.8'

services:
  site1:
    image: site1:v1
    container_name: site1
    ports:
      -"8081:80"

  site2:
    image: site2:v1
    container_name: site2
    ports:
      -"8082:80"

  haproxy:
    image: haproxy:latest
    container_name: haproxy2
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      -"443:443"